name: Minify CSS and JS

on:
  push:
    branches:
      - main

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Minify CSS
      run: npx uglifycss --output styles.min.css styles.css

    - name: Minify JS
      run: npx terser --compress --mangle --output script.min.js script.js

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add styles.min.css script.min.js
        git commit -m "Minify CSS and JS"
        git push origin main
        
